#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# Cursor 
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Wayland for apps
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = OZONE_PLATFORM,wayland
env = MOZ_ENABLE_WAYLAND,1

# GTK
env = GTK_USE_PORTAL,1
env = GTK_THEME,Catppuccin-Mocha-Hyprland-Dark

# QT
env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1


